// const images = {
//     // profile: {
//     //     profile: require('./profile/profile.png'),
//     //     comments: require('./profile/comments.png'),
//     // },
//     adam: require('./adam.jpg'),
//     billy: require('./billy.jpg'),
//     charlie: require('./charlie.jpg'),
//     david: require('./david.jpg'),
//     eddy: require('./eddy.jpg'),
//     freddie: require('./freddie.jpg'),
//     george: require('./george.jpg'),
//     harry: require('./harry.jpg'),
//     ian: require('./ian.jpg'),
//     jane: require('./jane.jpg'),
//     kevin: require('./kevin.jpg'),
//     lucy: require('./lucy.jpg'),
//     marilyn: require('./marilyn.jpg'),
//     nancy: require('./nancy.jpg'),
//     oliver: require('./oliver.jpg'),
//     peter: require('./peter.jpg'),
//     quentin: require('./quentin.jpg'),
//     ronald: require('./ronald.jpg'),
//     steven: require('./steven.jpg'),
//     tony: require('./tony.jpg'),
//     ursula: require('./ursula.jpg'),
//     vince: require('./vince.jpg'),
//     william: require('./william.jpg'),
//     xteve: require('./xteve.jpg'),
//     yvette: require('./yvette.jpg'),
//     zinedine: require('./zinedine.jpg'),
// };

const images = [
    // profile: {
    //     profile: require('./profile/profile.png'),
    //     comments: require('./profile/comments.png'),
    // },
    require('./adam.jpg'),
    require('./billy.jpg'),
    require('./charlie.jpg'),
    require('./david.jpg'),
    require('./eddy.jpg'),
    require('./freddie.jpg'),
    require('./george.jpg'),
    require('./harry.jpg'),
    require('./ian.jpg'),
    require('./jane.jpg'),
    require('./kevin.jpg'),
    require('./lucy.jpg'),
    require('./marilyn.jpg'),
    require('./nancy.jpg'),
    require('./oliver.jpg'),
    require('./peter.jpg'),
    require('./quentin.jpg'),
    require('./ronald.jpg'),
    require('./steven.jpg'),
    require('./tony.jpg'),
    require('./ursula.jpg'),
    require('./vince.jpg'),
    require('./william.jpg'),
    require('./xteve.jpg'),
    require('./yvette.jpg'),
    require('./zinedine.jpg'),
];

export default images;
